# Generated by Django 5.2.6 on 2025-12-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
